CREATE TABLE "players" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"beatLeaderId" varchar(32),
	"steamId" varchar(32),
	"oculusId" varchar(32),
	"questId" integer,
	"alias" varchar(32),
	"scoreSaberId" varchar(32),
	"scoreSaberAlias" varchar(32),
	"accSaberId" varchar(32),
	"hitBloqId" integer,
	"name" text NOT NULL,
	"avatar" text DEFAULT '' NOT NULL,
	"blRankHistory" jsonb,
	"ssRankHistory" jsonb,
	"asRankHistory" jsonb,
	"overallRankHistory" jsonb,
	"totalScores" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rankfeeds" (
	"id" serial PRIMARY KEY NOT NULL,
	"type" varchar(32) NOT NULL,
	"channelType" varchar(32) NOT NULL,
	"displayType" varchar(32) NOT NULL,
	"userId" varchar(32),
	"channelId" varchar(32),
	"guildId" varchar(32),
	"managerRoleId" varchar(32),
	"playerIds" varchar(32)[] NOT NULL,
	"hasFilters" boolean NOT NULL,
	"ssRanked" boolean,
	"blRanked" boolean,
	"asRanked" boolean,
	"minRank" integer
);
--> statement-breakpoint
CREATE TABLE "scorefeeds" (
	"id" serial PRIMARY KEY NOT NULL,
	"type" varchar(32) NOT NULL,
	"channelType" varchar(32) NOT NULL,
	"displayType" varchar(32) NOT NULL,
	"userId" varchar(32),
	"channelId" varchar(32),
	"guildId" varchar(32),
	"managerRoleId" varchar(32),
	"playerIds" varchar(32)[] NOT NULL,
	"hasFilters" boolean NOT NULL,
	"ssRanked" boolean,
	"blRanked" boolean,
	"asRanked" boolean,
	"minRank" integer
);
--> statement-breakpoint
CREATE TABLE "scores" (
	"id" serial PRIMARY KEY NOT NULL,
	"playerId" varchar(32) NOT NULL,
	"provider" varchar(32)[] NOT NULL,
	"playerName" text DEFAULT '' NOT NULL,
	"playerAvatar" text DEFAULT '' NOT NULL,
	"songName" text DEFAULT '' NOT NULL,
	"songSubname" text DEFAULT '' NOT NULL,
	"songAuthor" text DEFAULT '' NOT NULL,
	"songCover" text DEFAULT '' NOT NULL,
	"mapAuthor" text DEFAULT '' NOT NULL,
	"songHash" varchar(64) NOT NULL,
	"songDifficulty" varchar(64) NOT NULL,
	"songCharacteristic" varchar(128) NOT NULL,
	"score" integer NOT NULL,
	"accuracy" double precision NOT NULL,
	"fullCombo" boolean NOT NULL,
	"missedNotes" integer NOT NULL,
	"badCuts" integer NOT NULL,
	"bombHits" integer,
	"wallHits" integer,
	"ppBL" integer DEFAULT 0 NOT NULL,
	"ppSS" integer DEFAULT 0 NOT NULL,
	"ap" integer DEFAULT 0 NOT NULL,
	"modifiers" varchar(32)[],
	"improvement" double precision,
	"blLeaderboardId" integer,
	"blScoreId" integer,
	"blRank" integer,
	"ssLeaderboardId" integer,
	"ssScoreId" integer,
	"ssRank" integer,
	"outdated" boolean NOT NULL,
	"timestamp" timestamp NOT NULL,
	"messageIds" varchar(32)[],
	"upVoteIds" varchar(32)[] NOT NULL,
	"downVoteIds" varchar(32)[] NOT NULL
);
