CREATE TABLE "players" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"beatLeaderId" varchar(32),
	"steamId" varchar(32),
	"oculusId" varchar(32),
	"questId" integer,
	"alias" varchar(32),
	"scoreSaberId" varchar(32),
	"scoreSaberAlias" varchar(32),
	"accSaberId" varchar(32),
	"hitBloqId" integer,
	"name" text NOT NULL,
	"avatar" text DEFAULT '' NOT NULL,
	"blRankHistory" jsonb,
	"ssRankHistory" jsonb,
	"asRankHistory" jsonb,
	"overallRankHistory" jsonb,
	"totalScores" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rankfeeds" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "rankfeeds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" varchar(32) NOT NULL,
	"channelType" varchar(32) NOT NULL,
	"displayType" varchar(32) NOT NULL,
	"userId" varchar(32),
	"channelId" varchar(32),
	"guildId" varchar(32),
	"managerRoleId" varchar(32),
	"playerIds" varchar(32)[] NOT NULL,
	"hasFilters" boolean NOT NULL,
	"ssRanked" boolean,
	"blRanked" boolean,
	"asRanked" boolean,
	"minRank" integer
);
--> statement-breakpoint
CREATE TABLE "scorefeeds" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "scorefeeds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" varchar(32) NOT NULL,
	"channelType" varchar(32) NOT NULL,
	"displayType" varchar(32) NOT NULL,
	"userId" varchar(32),
	"channelId" varchar(32),
	"guildId" varchar(32),
	"managerRoleId" varchar(32),
	"playerIds" varchar(32)[] NOT NULL,
	"hasFilters" boolean NOT NULL,
	"ssRanked" boolean,
	"blRanked" boolean,
	"asRanked" boolean,
	"minRank" integer
);
--> statement-breakpoint
CREATE TABLE "scoremessages" (
	"id" integer NOT NULL,
	"type" varchar(32) NOT NULL,
	"messageId" varchar(32) PRIMARY KEY NOT NULL,
	"userId" varchar(32),
	"channelId" varchar(32),
	"guildId" varchar(32)
);
--> statement-breakpoint
CREATE TABLE "scores" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "scores_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"playerId" varchar(32) NOT NULL,
	"provider" varchar(32)[] NOT NULL,
	"playerName" text DEFAULT '' NOT NULL,
	"playerAvatar" text DEFAULT '' NOT NULL,
	"songName" text DEFAULT '' NOT NULL,
	"songSubname" text DEFAULT '' NOT NULL,
	"songAuthor" text DEFAULT '' NOT NULL,
	"songCover" text DEFAULT '' NOT NULL,
	"mapAuthor" text DEFAULT '' NOT NULL,
	"songHash" varchar(64) NOT NULL,
	"songDifficulty" varchar(64) NOT NULL,
	"songCharacteristic" varchar(128) NOT NULL,
	"score" integer NOT NULL,
	"accuracy" double precision NOT NULL,
	"fullCombo" boolean NOT NULL,
	"missedNotes" integer NOT NULL,
	"badCuts" integer NOT NULL,
	"bombHits" integer,
	"wallHits" integer,
	"ppBL" double precision DEFAULT 0 NOT NULL,
	"ppSS" double precision DEFAULT 0 NOT NULL,
	"ap" double precision DEFAULT 0 NOT NULL,
	"modifiers" varchar(32)[],
	"improvement" double precision,
	"blLeaderboardId" varchar(32),
	"blScoreId" integer,
	"blStarRating" double precision,
	"blRank" integer,
	"ssLeaderboardId" integer,
	"ssScoreId" integer,
	"ssStarRating" double precision,
	"ssRank" integer,
	"outdated" boolean NOT NULL,
	"timestamp" timestamp NOT NULL,
	"messages" jsonb,
	"upVoteIds" varchar(32)[] NOT NULL,
	"downVoteIds" varchar(32)[] NOT NULL
);
